### ISSUE TITLE
The demo site is broken

### ISSUE THREAD

**Issue by billzt** [tgvaughan/icytree#41]
When I visit demo site: http://tgvaughan.github.io/icytree , it automatically turn to http://ww29.icytree.org/ , and show nothing

**Comment by tgvaughan** [comment]
Hi @billzt, sorry about this: I've just registered icytree.org and am waiting for DNS to update (which can take up to a day).  What you're seeing is a result of github redirecting to to the new address, but because the propagation isn't complete you're just seeing a parking page.  I'll see if I can adjust the github page settings so that things continue to work while DNS sorts itself out...

Thanks for pointing this out.

**Comment by tgvaughan** [comment]
Site now seems to be functional again.

**Comment by tgvaughan** [comment]
@billzt DNS propagation seems to be complete, so I've reenabled the custom domain on github.  Please let me know if you encounter this problem again.  Thanks.

**Comment by billzt** [comment]
That's OK
