### ISSUE TITLE
parsing failures not so informative

### ISSUE THREAD

**Issue by matsen** [tgvaughan/icytree#42]
Hallo Tim!

I'm prepping a workshop on phylogenetics, and tried plopping the output of phylogeny.fr into IcyTree. It turns out that the trees that phylogeny.fr produces have linebreaks within the tree! 

IcyTree said `Cannot read property '0' of undefined` which wasn't so helpful if I didn't already know what might be wrong with the tree.

Thanks.

**Comment by tgvaughan** [comment]
Thanks Erick, I agree this error message is weird and unhelpful.  Furthermore, line-breaks shouldn't cause a problem.  I'll have to fix that.  Do you have an example problem phylogeny.fr tree on hand?  (I.e. are line breaks the only problem with these files?)

**Comment by tgvaughan** [comment]
Hi again Erick, I've fixed the problem.  The preprocessor was splitting the input string into newline delimited substrings.  It was doing this to cope with files containing multiple newick strings with newlines separating them.  This meant that in the phylogeny.fr case the parser was being fed fragments of the original newick string rather than the whole thing.  The weird error was actually a bug in the parse error reporting code - it wasn't sensibly reporting when the token stream was prematurely terminated.

Since the update, files containing one or more newick strings are split based on the regex `/;\s*\n/` and a note is now in the manual which points out that when multiple newick strings are included in a file, each string must be terminated by a semicolon (which strictly speaking is meant to be the case anyway, but sometimes isn't in practice).  I've also fixed the error reporting, so the original file would have yielded an error stating that the newick string ended prematurely.  (Of course it doesn't generate an error now!)
